### ISSUE TITLE
不同点云文件差异较大

### ISSUE THREAD

**Issue by MengWangTHU** [wangx1996/LIDAR-Segmentation-Based-on-Range-Imag#1]
hi 作者：
感谢您的工作。
我把您的代码跑了一遍，但使用的1.7的pcl库。结果显示，您给出的样例点云文件跑出的结果是正常的，但使用其他的点云文件抛出的结果都不太好，不管是32线的还是64线的。请问关于这种现象有可能是什么样的原因？
另外，我查看了您的点云数据forange.pcd文件，里面的数据是常规的x/y/z/intensity，但我发现第4个数据有好多负值，比如-1，-0.009998， 这与intensity是常规的0~255之间的整值有悖，请问这里会有什么问题？

期待您的解答。

**Comment by wangx1996** [comment]
@MengWangTHU 你好，我给出的点云是velodyne32线的点云，其中intensity的值被我换成了点的测量距离。这个距离值是解析原始点云数据的时候得出的，因为我要用到这个数据来滤除那些没有反射回来的点，为了省事没有自建一个pcl格式，因此正如你看到的他会有负值，表明这个点没有被接收或者解析有问题。你可以试着自建一个点云格式来解决这个问题，其他的如果效果还不太好的话，先确定一下深度图的生成是否正确。

**Comment by MengWangTHU** [comment]
@wangx1996 感谢您的回答，顺祝新年开工工作顺利！
您提到您用的“velodyne32线的点云，其中intensity的值被我换成了点的测量距离”；我又看了forange.pcd，发现其中第四维”intensity“数据并非前三维平方和开根号，而是总比其中一维（尤其是y方向）略小。出现这个问题是否是因为，这个数据是您直接“是解析原始点云数据的时候得出的”，而并非平方和开根号得出的？

**Comment by wangx1996** [comment]
@MengWangTHU 有可能是这样的

**Comment by MengWangTHU** [comment]
@wangx1996 您好！
目前我跑您的程序使用的数据是已经生成的32线pcd文件，只有x/y/z/i四维，没有原始的range数据，我将其中第四维用前三项的平方和开根号进行替换，结果仍然不够好；查看了生成的深度图，不像您给的pcd文件生成的生成的深度图可以明显看出不同障碍物的语义，我自己的数据生成的深度图仍然非常糟糕。
不知我是否错过了一些比较关键的处理，尤其是第四维的数据？
期待您的解答！

**Comment by wangx1996** [comment]
@MengWangTHU 如果深度图生成存在问题的话应该是点云文件里点云的排布顺序和我的pcd文件不太一样，可以根据你的点云文件的排布顺序进行生成，也可以关注下我的代码中深度图生成那部分

**Comment by PhoenixZqh** [comment]
你好，请问下点云扫描线补偿是代码中哪个函数实现的

**Comment by Liuyaqi99** [comment]
您好，想请问下如果想适配到自己的点云数据上（非velodyne），第四维应该如何生成呢？十分感谢
