### ISSUE TITLE
自己的点云文件怎么转换成项目所用的点云格式呢

### ISSUE THREAD

**Issue by lfxx** [wangx1996/LIDAR-Segmentation-Based-on-Range-Imag#2]
如果没有点的测量距离就不能用了吗，或者说能否自己生成这个值呢。另外点云外面还有一个大圈，这个可否自己生成呢？

**Comment by wangx1996** [comment]
@lfxx 
可以自己通过点的坐标进行计算，外面的大圈指的是未返回的点，直接忽略即可
